### ISSUE TITLE
Searching associated: enum field

### ISSUE THREAD

**Issue by killthekitten** [railsadminteam/rails_admin#1080]
Imagine, that we have got Model with enum field :state and AssociatedModel. When we are trying to attach AssociatedModel to Model from rails_admin interface, the search query fails: it tries to match string and integer.

This bug hides in `lib/rails_admin/adapters/active_record.rb` within `build_statement` method:

```
when :enum
  return if value.blank?
  ["(#{column} IN (?))", Array.wrap(value)]
end
```

This piece of code generates something like `...state IN ('Search string')`
It must return from method in case `if value.blank? || value.is_a?(String)` or something like that.

**Comment by kmanzana** [comment]
We are also experiencing the same issues for a role enum method and being able to search.  Any updates?  Is this still a bug?

cc @raghugjoshi

**Comment by simonfranzen** [comment]
Thats crazy. It did not work for me and I came to a thread where they say: "Add a method enum_role and this fixes your problem". Now I am here and I have to remove my method again. A bit confusing, but in the end it worked. Can someone explain in what version this ENUM chaos was fixed ?

**Comment by simonfranzen** [comment]
We are still having problems getting the search work with enums...

**Comment by hamdi777** [comment]
field :your_enum, :enum do
	enum do
	  [ %w(first_option 0), %w(second_option 1), %w(third_option 2) ]
	end
end

this will fix the issue with filtering your enums and it will search by the integer key but problem persists in blank and present
