### ISSUE TITLE
error while updating user

### ISSUE THREAD

**Issue by xxxazxxx** [railsadminteam/rails_admin#2107]
rails_admin user editing :

```
ActiveRecord::RecordNotUnique in RailsAdmin::MainController#edit
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "users_pkey" DETAIL: Key (id)=(1) already exists. : UPDATE "users" SET "current_sign_in_at" = $1, "first_name" = $2, "id" = $3, "is_admin" = $4, "last_sign_in_at" = $5, "unconfirmed_email" = $6, "updated_at" = $7 WHERE "users"."id" = 3

Extracted source (around line #74):
72
73
74
75
76
77

    old_time_zone = Time.zone
    Time.zone = current_user.time_zone if user_signed_in?
    yield
  ensure
    Time.zone = old_time_zone
  end

Rails.root: /home/admin/ror/aurum

Application Trace | Framework Trace | Full Trace
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `get_last_result'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `block in exec_cache'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:831:in `exec_cache'
vendor/bundle/ruby/2.1.0/gems/schema_plus-1.6.0/lib/schema_plus/active_record/connection_adapters/postgresql_adapter.rb:237:in `exec_cache_with_schema_plus'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `exec_delete'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `update'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `update'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:84:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/persistence.rb:494:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/locking/optimistic.rb:70:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:83:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:310:in `block in _update_record'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:310:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/timestamp.rb:70:in `_update_record'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/persistence.rb:483:in `create_or_update'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `create_or_update'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/persistence.rb:103:in `save'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/validations.rb:51:in `save'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:21:in `save'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:268:in `block in save'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/transactions.rb:267:in `save'
vendor/bundle/ruby/2.1.0/gems/rails_admin-0.6.5/lib/rails_admin/adapters/active_record/abstract_object.rb:23:in `save'
vendor/bundle/ruby/2.1.0/gems/rails_admin-0.6.5/lib/rails_admin/config/actions/edit.rb:33:in `block (2 levels) in <class:Edit>'
(eval):8:in `instance_eval'
(eval):8:in `edit'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:299:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:299:in `block (2 levels) in halting'
app/controllers/application_controller.rb:74:in `set_time_zone'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:424:in `block in make_lambda'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:298:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:298:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
vendor/bundle/ruby/2.1.0/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `public_send'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `method_missing'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/error_collector.rb:50:in `traced_call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/migration.rb:380:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:13:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/rack/logger.rb:22:in `call'
vendor/bundle/ruby/2.1.0/gems/quiet_assets-1.0.3/lib/quiet_assets.rb:23:in `call_with_quiet_assets'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/static.rb:64:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
vendor/bundle/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
vendor/bundle/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/home/admin/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/home/admin/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/home/admin/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
Request


```

**Comment by xxxazxxx** [comment]
any updates with this error?
Users need to login to console to reset their password.

**Comment by mdkirby** [comment]
I think somewhere, nil.id is being called, which returns 4. I can update the user with the id 4, but I get errors for any other users.

Success for User #4
```
Started PUT "/admin/user/4/edit" for [FILTERED] at 2015-01-22 17:25:30 +0000
Processing by RailsAdmin::MainController#edit as HTML
  Parameters: {
    "utf8"=>"✓", 
    "authenticity_token"=>"[FILTERED]", 
    "user"=>{"first_name"=>"[FILTERED]", "last_name"=>"[FILTERED]", "image_url"=>"", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "reset_password_sent_at"=>"[FILTERED]", "remember_created_at"=>"January 22, 2015 16:49", "sign_in_count"=>"2", "current_sign_in_at"=>"January 22, 2015 16:49", "last_sign_in_at"=>"January 22, 2015 16:17", "current_sign_in_ip"=>"[FILTERED]", "last_sign_in_ip"=>"[FILTERED]", "confirmation_token"=>"", "confirmed_at"=>"", "confirmation_sent_at"=>"", "unconfirmed_email"=>"", "failed_attempts"=>"0", "unlock_token"=>"", "locked_at"=>"", "is_admin"=>"1", "authentication_ids"=>["", ""]}, 
    "return_to"=>"[FILTERED]", 
    "_save"=>"", 
    "model_name"=>"user", 
    "id"=>"4"}
Redirected to [FILTERED]
Completed 302 Found in 40ms (ActiveRecord: 7.4ms)
```
Notice the **"id"=>"4"**

Failure for User #6
```
Started PUT "/admin/user/6/edit" for [FILTERED] at 2015-01-22 17:39:19 +0000
Processing by RailsAdmin::MainController#edit as HTML
  Parameters: {
    "utf8"=>"✓", 
    "authenticity_token"=>"[FILTERED]", 
    "user"=>{"first_name"=>"[FILTERED]", "last_name"=>"", "image_url"=>"", "email"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "reset_password_sent_at"=>"[FILTERED]", "remember_created_at"=>"", "sign_in_count"=>"1", "current_sign_in_at"=>"January 22, 2015 16:49", "last_sign_in_at"=>"January 22, 2015 16:49", "current_sign_in_ip"=>"[FILTERED]", "last_sign_in_ip"=>"[FILTERED]", "confirmation_token"=>"", "confirmed_at"=>"", "confirmation_sent_at"=>"", "unconfirmed_email"=>"", "failed_attempts"=>"0", "unlock_token"=>"", "locked_at"=>"", "is_admin"=>"1", "authentication_ids"=>["", ""]}, 
    "return_to"=>"[FILTERED]/admin/user/6", "_save"=>"", 
    "model_name"=>"user", 
    "id"=>"6"}
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(4) already exists.
: UPDATE "users" SET "first_name" = $1, "last_name" = $2, "image_url" = $3, "confirmation_token" = $4, "unconfirmed_email" = $5, "unlock_token" = $6, "current_sign_in_at" = $7, "last_sign_in_at" = $8, "id" = $9, "updated_at" = $10 WHERE "users"."id" = $11
Completed 500 Internal Server Error in 1033ms

ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(4) already exists.
: UPDATE "users" SET "first_name" = $1, "last_name" = $2, "image_url" = $3, "confirmation_token" = $4, "unconfirmed_email" = $5, "unlock_token" = $6, "current_sign_in_at" = $7, "last_sign_in_at" = $8, "id" = $9, "updated_at" = $10 WHERE "users"."id" = $11):
```

**Comment by pkmishra** [comment]
Any update on this issue? It seems problem is with cancan(can) integration. Here is the work around in the mean time ...
1) remove cancan as authorization mechanism from rails admin config. 
2) Use following code 
```
config.authorize_with do
      redirect_to main_app.root_path unless warden.user.is_admin?
end
```

**Comment by P9GIT** [comment]
+1

We're seeing a similar issue (version 0.8.1).
When changing password on one user rails admin changes the password of another user (the current user logged in).

**Comment by P9GIT** [comment]
@lazebny 

Hi, thanks for getting back on this issue.

We have since moved to version 1.1.1.

To re-test this problem I just created a new Admin user (admin role), logged in with it and tried to update the password on another admin user.
It worked as expected with no adverse effects on the current user.

So I think the observed bug is solved, at least for my part.

Thanks!

**Comment by farmisen** [comment]
Still experiencing the problem with rails_admin-1.2.0:

> **PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "users_pkey" DETAIL: Key (id)=(1) already exists. : UPDATE "users" SET "id" = $1, "role" = $2, "updated_at" = $3 WHERE "users"."id" = $4**


```
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql_adapter.rb:620:in `async_exec'
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql_adapter.rb:620:in `block (2 levels) in exec_no_cache'
activesupport (5.1.2) lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
activesupport (5.1.2) lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
activesupport (5.1.2) lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql_adapter.rb:619:in `block in exec_no_cache'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/farmisen/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql_adapter.rb:618:in `exec_no_cache'
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql_adapter.rb:607:in `execute_and_clear'
activerecord (5.1.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec_delete'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:130:in `update'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
activerecord (5.1.2) lib/active_record/relation.rb:85:in `_update_record'
activerecord (5.1.2) lib/active_record/persistence.rb:575:in `_update_record'
activerecord (5.1.2) lib/active_record/locking/optimistic.rb:80:in `_update_record'
activerecord (5.1.2) lib/active_record/attribute_methods/dirty.rb:292:in `_update_record'
activerecord (5.1.2) lib/active_record/callbacks.rb:344:in `block in _update_record'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
airbrake (6.2.0) lib/airbrake/rails/active_record.rb:22:in `run_callbacks'
activesupport (5.1.2) lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
activerecord (5.1.2) lib/active_record/callbacks.rb:344:in `_update_record'
activerecord (5.1.2) lib/active_record/timestamp.rb:107:in `_update_record'
activerecord (5.1.2) lib/active_record/persistence.rb:563:in `create_or_update'
activerecord (5.1.2) lib/active_record/callbacks.rb:336:in `block in create_or_update'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
airbrake (6.2.0) lib/airbrake/rails/active_record.rb:22:in `run_callbacks'
activesupport (5.1.2) lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
activerecord (5.1.2) lib/active_record/callbacks.rb:336:in `create_or_update'
activerecord (5.1.2) lib/active_record/persistence.rb:129:in `save'
activerecord (5.1.2) lib/active_record/validations.rb:44:in `save'
activerecord (5.1.2) lib/active_record/attribute_methods/dirty.rb:35:in `save'
activerecord (5.1.2) lib/active_record/transactions.rb:308:in `block (2 levels) in save'
activerecord (5.1.2) lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/farmisen/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
activerecord (5.1.2) lib/active_record/transactions.rb:210:in `transaction'
activerecord (5.1.2) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
activerecord (5.1.2) lib/active_record/transactions.rb:308:in `block in save'
activerecord (5.1.2) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
activerecord (5.1.2) lib/active_record/transactions.rb:307:in `save'
activerecord (5.1.2) lib/active_record/suppressor.rb:42:in `save'
newrelic_rpm (4.3.0.335) lib/new_relic/agent/instrumentation/active_record_5.rb:15:in `block in save'
newrelic_rpm (4.3.0.335) lib/new_relic/agent/transaction.rb:859:in `with_database_metric_name'
newrelic_rpm (4.3.0.335) lib/new_relic/agent.rb:587:in `with_database_metric_name'
newrelic_rpm (4.3.0.335) lib/new_relic/agent/instrumentation/active_record_5.rb:14:in `save'
rails_admin (1.2.0) lib/rails_admin/adapters/active_record/abstract_object.rb:23:in `save'
rails_admin (1.2.0) lib/rails_admin/config/actions/edit.rb:35:in `block (2 levels) in <class:Edit>'
rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:25:in `instance_eval'
rails_admin (1.2.0) app/controllers/rails_admin/main_controller.rb:25:in `edit'
```

**Parameters:**
```
{"utf8"=>"✓",
 "_method"=>"put",
 "authenticity_token"=>"dU7289xh182Yya8Ernnrfcb6XoexYSkgUjCSJSTdjBbP7oOpyoehrSgBcDRxTl0IJa8Nvih3Xgkj1rbuOox1VA==",
 "user"=>{"email"=>"user@example.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "role"=>"publisher"},
 "return_to"=>"http://localhost:3000/cms/user",
 "_save"=>"",
 "model_name"=>"user",
 "id"=>"2"}
```

**Comment by applecrusher** [comment]
@farmisen The only way I got it to work was to do what pkmishra did with cancan (above) and then creating the table without any indexes in the create_users migrate folder. 

So it would just be commenting out like such

```
    #add_index :users, :reset_password_token, unique: true
    #add_index :users, :confirmation_token, unique: true
    #add_index :users, :unlock_token, unique: true
```

**Comment by jdefrance-stessa** [comment]
I wouldn't recommend removing these indexes and uniqueness constraints from the user table.

Have you tried the following approach instead, adding these couple of lines to the User model?

`  
  rails_admin do
    exclude_fields :reset_password_token, :confirmation_token, :unlock_token, :invitation_token
  end
`

**Comment by jdefrance-stessa** [comment]
> Duplicate of #1880.

I think the 2 issues are quite distinct.
